try{
  hello();
} catch (erro){
  console.log(error);
  
}

try{
  anotherFn();
} catch {
  console.log('Esto es un error');
  
}